spring.application.name=taskflow-app

spring.datasource.url=jdbc:postgresql://dpg-d7l15j8sfn5c73cro26g-a.oregon-postgres.render.com:5432/taskflow_db_6m6p
spring.datasource.username=taskflow_db_6m6p_user
spring.datasource.password=I5npSa6KysO6B7x8nREqxQv21LVcWSQO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
server.address=0.0.0.0

jwt.secret=mysecretkey123